---
abstract: 'Test if a POE process has nothing left to do'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::POE::Stopping
name: Test-POE-Stopping
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  POE: 1.310
  POE::API::Peek: 2.17
  Test::Builder: 0.80
  Test::More: 0.80
  YAML::Tiny: 1.38
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Test-POE-Stopping
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Test-POE-Stopping
version: 1.09
